### ISSUE TITLE
Error with Files after 25.0.7 or 26.0.2 update with enabled E2EE App : Cannot use object of type OC\\Files\\Node\\LazyUserFolder as array

### ISSUE THREAD

**Issue by Dual-0** [nextcloud/end_to_end_encryption#450]
### Steps to reproduce
1. install Nextcloud Update 26.0.2 over Updater
2. In Files are no files found
3. Error Message: Dieses Verzeichnis ist nicht verfügbar, bitte die Logdateien überprüfen oder den Administrator kontaktieren.

### Expected behaviour
Files should be shown as with disabled E2EE App

### Actual behaviour
Error is given when E2EE App is enabled

### Server configuration
Ubuntu 22.04
Nginx 1.25.0
PHP 8.2.6
Postgresql 15
Nextcloud 26.0.2

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here:
No errors have been found.
```
</details>

List of activated apps:

<details>
<summary>App report</summary>

```
Enabled:
  - activity: 2.18.0
  - admin_audit: 1.16.0
  - bruteforcesettings: 2.6.0
  - calendar: 4.3.4
  - cloud_federation_api: 1.9.0
  - comments: 1.16.0
  - contacts: 5.2.0
  - contactsinteraction: 1.7.0
  - dashboard: 7.6.0
  - dav: 1.25.0
  - deck: 1.9.2
  - external: 5.1.0
  - extract: 1.3.5
  - federatedfilesharing: 1.16.0
  - federation: 1.16.0
  - files: 1.21.1
  - files_external: 1.18.0
  - files_pdfviewer: 2.7.0
  - files_rightclick: 1.5.0
  - files_sharing: 1.18.0
  - files_trashbin: 1.16.0
  - files_versions: 1.19.1
  - gpoddersync: 3.8.0
  - groupfolders: 14.0.2
  - integration_deepl: 1.1.0
  - integration_openai: 1.0.8
  - integration_replicate: 1.0.6
  - logreader: 2.11.0
  - lookup_server_connector: 1.14.0
  - mail: 3.1.1
  - metadata: 0.18.0
  - nextcloud_announcements: 1.15.0
  - notes: 4.7.2
  - notifications: 2.14.0
  - notify_push: 0.6.3
  - oauth2: 1.14.0
  - password_policy: 1.16.0
  - photos: 2.2.0
  - previewgenerator: 5.3.0
  - privacy: 1.10.0
  - provisioning_api: 1.16.0
  - recommendations: 1.5.0
  - related_resources: 1.1.0-alpha1
  - serverinfo: 1.16.0
  - settings: 1.8.0
  - sharebymail: 1.16.0
  - suspicious_login: 4.4.0
  - systemtags: 1.16.0
  - tables: 0.5.0
  - tasks: 0.15.0
  - text: 3.7.2
  - text_templates: 1.0.1
  - theming: 2.1.1
  - twofactor_backupcodes: 1.15.0
  - twofactor_nextcloud_notification: 3.7.0
  - twofactor_totp: 8.0.0
  - updatenotification: 1.16.0
  - user_status: 1.6.0
  - viewer: 1.10.0
  - weather_status: 1.6.0
  - webhooks: 0.4.3
  - workflow_script: 1.11.1
  - workflowengine: 2.8.0
Disabled:
  - circles: 26.0.0 (installed 24.0.0)
  - encryption: 2.14.0 (installed 2.2.0)
  - end_to_end_encryption: 1.12.4 (installed 1.12.4)
  - firstrunwizard: 2.15.0 (installed 2.3.0)
  - support: 1.9.0 (installed 1.3.0)
  - survey_client: 1.14.0 (installed 1.10.0)
  - user_ldap: 1.16.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***hidden***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "26.0.2.1",
        "overwrite.cli.url": "https:\/\/***hidden***",
        "htaccess.RewriteBase": "\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "5432",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "",
        "default_language": "de",
        "default_phone_region": "DE",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtptimeout": 10,
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 1,
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "logtimezone": "Europe\/Berlin",
        "data-fingerprint": "***hidden***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "dbindex": 0
        },
        "trashbin_retention_obligation": "auto, 90",
        "versions_retention_obligation": "auto, 30",
        "tempdirectory": "\/tmp",
        "cache_path": "\/var\/cache\/nextcloud",
        "localstorage.allowsymlinks": true,
        "enable_previews": "true",
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "preview_max_scale_factor": 1,
        "jpeg_quality": "60",
        "theme": "",
        "maintenance": false,
        "app_install_overwrite": [
            "end_to_end_encryption",
            "groupfolders",
            "workflow_script",
            "webhooks",
            "extract",
            "gpoddersync",
            "metadata"
        ],
        "updater.release.channel": "stable",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

#### Nextcloud log (data/nextcloud.log)

<details>
<summary>Logs</summary>
```
Insert your Nextcloud log here[webdav] Fehler: Error: Cannot use object of type OC\Files\Node\LazyUserFolder as array at <<closure>>

 0. /var/www/nextcloud/apps/end_to_end_encryption/lib/E2EEnabledPathCache.php line 56
    OCA\EndToEndEncryption\E2EEnabledPathCache->getEncryptedStates()
 1. /var/www/nextcloud/apps/end_to_end_encryption/lib/Connector/Sabre/APlugin.php line 105
    OCA\EndToEndEncryption\E2EEnabledPathCache->isE2EEnabledPath()
 2. /var/www/nextcloud/apps/end_to_end_encryption/lib/Connector/Sabre/RedirectRequestPlugin.php line 187
    OCA\EndToEndEncryption\Connector\Sabre\APlugin->isE2EEnabledPath()
 3. /var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    OCA\EndToEndEncryption\Connector\Sabre\RedirectRequestPlugin->propFind()
 4. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1052
    Sabre\DAV\Server->emit()
 5. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 984
    Sabre\DAV\Server->getPropertiesByNode()
 6. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1662
    Sabre\DAV\Server->getPropertiesIteratorForPath()
 7. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1647
    Sabre\DAV\Server->writeMultiStatus()
 8. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 346
    Sabre\DAV\Server->generateMultiStatus()
 9. /var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpPropFind()
10. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 472
    Sabre\DAV\Server->emit()
11. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 253
    Sabre\DAV\Server->invokeMethod()
12. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 321
    Sabre\DAV\Server->start()
13. /var/www/nextcloud/apps/dav/lib/Server.php line 366
    Sabre\DAV\Server->exec()
14. /var/www/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
15. /var/www/nextcloud/remote.php line 172
    require_once("/var/www/nextcl ... p")

PROPFIND /remote.php/dav/files/hidden_username/
```

**Comment by BrianBlaze** [comment]
I am having the same issue with the same OS and PHP version but using apache and mysql. My logs look the same.

**Comment by delorean44** [comment]
under 25.07 same error.

**Comment by raczkow** [comment]
> under 25.07 same error.

Broken on my system too after updating to 25.07

**Comment by Dual-0** [comment]
Can you guys please use the thumb up 👍 reaction to show how many users have this issue. I think this can help the devs to prioritize.

**Comment by solracsf** [comment]
Error stack:

```
{
  "reqId": "JqCDoWfEzjLlvrE4yAj4",
  "level": 3,
  "time": "2023-05-26T10:23:12+02:00",
  "app": "webdav",
  "method": "PROPFIND",
  "url": "/remote.php/webdav",
  "message": "Cannot use object of type OC\\Files\\Node\\LazyUserFolder as array",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
  "version": "25.0.7.1",
  "exception": {
    "Exception": "Error",
    "Message": "Cannot use object of type OC\\Files\\Node\\LazyUserFolder as array",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/nextcloud/apps/end_to_end_encryption/lib/E2EEnabledPathCache.php",
        "line": 56,
        "function": "getEncryptedStates",
        "class": "OCA\\EndToEndEncryption\\E2EEnabledPathCache",
        "type": "->",
        "args": [
          [
            "OC\\Files\\Cache\\HomeCache"
          ],
          [
            "OC\\Files\\Node\\Folder"
          ],
          [
            "OCA\\Files_Trashbin\\Storage",
            null,
            [
              "OC\\Files\\Cache\\Scanner"
            ],
            null,
            null,
            null
          ]
        ]
      },
      {
        "file": "/var/www/nextcloud/apps/end_to_end_encryption/lib/Connector/Sabre/APlugin.php",
        "line": 105,
        "function": "isE2EEnabledPath",
        "class": "OCA\\EndToEndEncryption\\E2EEnabledPathCache",
        "type": "->",
        "args": [
          [
            "OC\\Files\\Node\\Folder"
          ]
        ]
      },
      {
        "file": "/var/www/nextcloud/apps/end_to_end_encryption/lib/Connector/Sabre/RedirectRequestPlugin.php",
        "line": 187,
        "function": "isE2EEnabledPath",
        "class": "OCA\\EndToEndEncryption\\Connector\\Sabre\\APlugin",
        "type": "->",
        "args": [
          [
            "OCA\\DAV\\Connector\\Sabre\\Directory"
          ]
        ]
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "propFind",
        "class": "OCA\\EndToEndEncryption\\Connector\\Sabre\\RedirectRequestPlugin",
        "type": "->",
        "args": [
          [
            "Sabre\\DAV\\PropFind"
          ],
          [
            "OCA\\DAV\\Connector\\Sabre\\Directory"
          ]
        ]
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 1052,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "propFind",
          [
            [
              "Sabre\\DAV\\PropFind"
            ],
            [
              "OCA\\DAV\\Connector\\Sabre\\Directory"
            ]
          ]
        ]
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 984,
        "function": "getPropertiesByNode",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          [
            "Sabre\\DAV\\PropFind"
          ],
          [
            "OCA\\DAV\\Connector\\Sabre\\Directory"
          ]
        ]
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 1662,
        "function": "getPropertiesIteratorForPath",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "",
          [
            "{DAV:}resourcetype"
          ],
          1
        ]
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 1647,
        "function": "writeMultiStatus",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          [
            "Sabre\\Xml\\Writer",
            [],
            "/remote.php/webdav/",
            [
              "d",
              "s",
              "oc",
              "nc"
            ],
            []
          ],
          [
            "Generator"
          ],
          false
        ]
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
        "line": 346,
        "function": "generateMultiStatus",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          [
            "Generator"
          ],
          false
        ]
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "httpPropFind",
        "class": "Sabre\\DAV\\CorePlugin",
        "type": "->",
        "args": [
          [
            "Sabre\\HTTP\\Request"
          ],
          [
            "Sabre\\HTTP\\Response"
          ]
        ]
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 472,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "method:PROPFIND",
          [
            [
              "Sabre\\HTTP\\Request"
            ],
            [
              "Sabre\\HTTP\\Response"
            ]
          ]
        ]
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 253,
        "function": "invokeMethod",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          [
            "Sabre\\HTTP\\Request"
          ],
          [
            "Sabre\\HTTP\\Response"
          ]
        ]
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 321,
        "function": "start",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/nextcloud/apps/dav/appinfo/v1/webdav.php",
        "line": 85,
        "function": "exec",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/nextcloud/remote.php",
        "line": 172,
        "args": [
          "/var/www/nextcloud/apps/dav/appinfo/v1/webdav.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/var/www/nextcloud/apps/end_to_end_encryption/lib/E2EEnabledPathCache.php",
    "Line": 90,
    "message": "Cannot use object of type OC\\Files\\Node\\LazyUserFolder as array",
    "exception": [],
    "CustomMessage": "Cannot use object of type OC\\Files\\Node\\LazyUserFolder as array"
  },
  "id": "64706cd390ce0"
}
```

**Comment by solracsf** [comment]
@artonge isn't this fixed by https://github.com/nextcloud/end_to_end_encryption/pull/430 (but not yet released?)

**Comment by artonge** [comment]
Versions with the fix just got released for 25 and 26. 24 is still pending

**Comment by Dual-0** [comment]
I download [v1.12.5](https://github.com/nextcloud-releases/end_to_end_encryption/releases/download/v1.12.5/end_to_end_encryption-v1.12.5.tar.gz) and unpack it into the app folder after deleting the old one. So I updated manually.

Still the same error:
```
[webdav] Fehler: Error: Cannot use object of type OC\Files\Node\LazyUserFolder as array at <<closure>>

 0. /var/www/nextcloud/apps/end_to_end_encryption/lib/E2EEnabledPathCache.php line 56
    OCA\EndToEndEncryption\E2EEnabledPathCache->getEncryptedStates()
 1. /var/www/nextcloud/apps/end_to_end_encryption/lib/Connector/Sabre/APlugin.php line 105
    OCA\EndToEndEncryption\E2EEnabledPathCache->isE2EEnabledPath()
 2. /var/www/nextcloud/apps/end_to_end_encryption/lib/Connector/Sabre/RedirectRequestPlugin.php line 187
    OCA\EndToEndEncryption\Connector\Sabre\APlugin->isE2EEnabledPath()
 3. /var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    OCA\EndToEndEncryption\Connector\Sabre\RedirectRequestPlugin->propFind()
 4. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1052
    Sabre\DAV\Server->emit()
 5. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 984
    Sabre\DAV\Server->getPropertiesByNode()
 6. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1662
    Sabre\DAV\Server->getPropertiesIteratorForPath()
 7. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1647
    Sabre\DAV\Server->writeMultiStatus()
 8. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 346
    Sabre\DAV\Server->generateMultiStatus()
 9. /var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpPropFind()
10. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 472
    Sabre\DAV\Server->emit()
11. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 253
    Sabre\DAV\Server->invokeMethod()
12. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 321
    Sabre\DAV\Server->start()
13. /var/www/nextcloud/apps/dav/appinfo/v1/webdav.php line 85
    Sabre\DAV\Server->exec()
14. /var/www/nextcloud/remote.php line 172
    require_once("/var/www/nextcl ... p")

PROPFIND /remote.php/webdav
```

Apps:
```
user@instance:/var/www/nextcloud# sudo -u www-data php occ app:list
Enabled:
  - activity: 2.18.0
  - admin_audit: 1.16.0
  - bruteforcesettings: 2.6.0
  - calendar: 4.3.4
  - cloud_federation_api: 1.9.0
  - comments: 1.16.0
  - contacts: 5.2.0
  - contactsinteraction: 1.7.0
  - dashboard: 7.6.0
  - dav: 1.25.0
  - deck: 1.9.2
  - end_to_end_encryption: 1.12.5
  - external: 5.1.0
  - extract: 1.3.5
  - federatedfilesharing: 1.16.0
  - federation: 1.16.0
  - files: 1.21.1
  - files_external: 1.18.0
  - files_pdfviewer: 2.7.0
  - files_rightclick: 1.5.0
  - files_sharing: 1.18.0
  - files_trashbin: 1.16.0
  - files_versions: 1.19.1
  - gpoddersync: 3.8.0
  - groupfolders: 14.0.2
  - integration_deepl: 1.1.0
  - integration_openai: 1.0.8
  - integration_replicate: 1.0.6
  - logreader: 2.11.0
  - lookup_server_connector: 1.14.0
  - mail: 3.1.1
  - metadata: 0.18.0
  - nextcloud_announcements: 1.15.0
  - notes: 4.7.2
  - notifications: 2.14.0
  - notify_push: 0.6.3
  - oauth2: 1.14.0
  - password_policy: 1.16.0
  - photos: 2.2.0
  - previewgenerator: 5.3.0
  - privacy: 1.10.0
  - provisioning_api: 1.16.0
  - recommendations: 1.5.0
  - related_resources: 1.1.0-alpha1
  - serverinfo: 1.16.0
  - settings: 1.8.0
  - sharebymail: 1.16.0
  - suspicious_login: 4.4.0
  - systemtags: 1.16.0
  - tables: 0.5.0
  - tasks: 0.15.0
  - text: 3.7.2
  - text_templates: 1.0.1
  - theming: 2.1.1
  - twofactor_backupcodes: 1.15.0
  - twofactor_nextcloud_notification: 3.7.0
  - twofactor_totp: 8.0.0
  - updatenotification: 1.16.0
  - user_status: 1.6.0
  - viewer: 1.10.0
  - weather_status: 1.6.0
  - webhooks: 0.4.3
  - workflow_script: 1.11.1
  - workflowengine: 2.8.0
Disabled:
  - circles: 26.0.0 (installed 24.0.0)
  - encryption: 2.14.0 (installed 2.2.0)
  - firstrunwizard: 2.15.0 (installed 2.3.0)
  - support: 1.9.0 (installed 1.3.0)
  - survey_client: 1.14.0 (installed 1.10.0)
  - user_ldap: 1.16.0
  ```

**Comment by artonge** [comment]
@ Can you share the json log?

**Comment by Dual-0** [comment]
yes of course
```
{"reqId":"IsXFi9ut68HOm5Erwjxg","level":1,"time":"2023-05-26T14:19:35+02:00","remoteAddr":"hidden.ip","user":"user","app":"no app in context","method":"GET","url":"/apps/files/","message":"Deprecated event type for \\OCP\\Collaboration\\Resources::loadAdditionalScripts: null","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36","version":"26.0.2.1","data":[]}
{"reqId":"IsXFi9ut68HOm5Erwjxg","level":1,"time":"2023-05-26T14:19:35+02:00","remoteAddr":"hidden.ip","user":"user","app":"no app in context","method":"GET","url":"/apps/files/","message":"Deprecated event type for OCA\\Files::loadAdditionalScripts: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36","version":"26.0.2.1","data":[]}
{"reqId":"3mok1oz3AX1kVhPZ9Kan","level":1,"time":"2023-05-26T14:19:37+02:00","remoteAddr":"hidden.ip","user":"user","app":"no app in context","method":"GET","url":"/apps/files/","message":"Deprecated event type for \\OCP\\Collaboration\\Resources::loadAdditionalScripts: null","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36","version":"26.0.2.1","data":[]}
{"reqId":"3mok1oz3AX1kVhPZ9Kan","level":1,"time":"2023-05-26T14:19:37+02:00","remoteAddr":"hidden.ip","user":"user","app":"no app in context","method":"GET","url":"/apps/files/","message":"Deprecated event type for OCA\\Files::loadAdditionalScripts: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36","version":"26.0.2.1","data":[]}
{"reqId":"nxd0CggwOjytp9SIMdDr","level":3,"time":"2023-05-26T14:19:40+02:00","remoteAddr":"hidden.ip","user":"user","app":"webdav","method":"PROPFIND","url":"/remote.php/dav/files/user/","message":"Cannot use object of type OC\\Files\\Node\\LazyUserFolder as array","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36","version":"26.0.2.1","exception":{"Exception":"Error","Message":"Cannot use object of type OC\\Files\\Node\\LazyUserFolder as array","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/end_to_end_encryption/lib/E2EEnabledPathCache.php","line":56,"function":"getEncryptedStates","class":"OCA\\EndToEndEncryption\\E2EEnabledPathCache","type":"->"},{"file":"/var/www/nextcloud/apps/end_to_end_encryption/lib/Connector/Sabre/APlugin.php","line":105,"function":"isE2EEnabledPath","class":"OCA\\EndToEndEncryption\\E2EEnabledPathCache","type":"->"},{"file":"/var/www/nextcloud/apps/end_to_end_encryption/lib/Connector/Sabre/RedirectRequestPlugin.php","line":187,"function":"isE2EEnabledPath","class":"OCA\\EndToEndEncryption\\Connector\\Sabre\\APlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"propFind","class":"OCA\\EndToEndEncryption\\Connector\\Sabre\\RedirectRequestPlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1052,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":984,"function":"getPropertiesByNode","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1662,"function":"getPropertiesIteratorForPath","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1647,"function":"writeMultiStatus","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":346,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":366,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/remote.php","line":172,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/end_to_end_encryption/lib/E2EEnabledPathCache.php","Line":90,"message":"Cannot use object of type OC\\Files\\Node\\LazyUserFolder as array","exception":{},"CustomMessage":"Cannot use object of type OC\\Files\\Node\\LazyUserFolder as array"}}
{"reqId":"49Jlq1hekntQ2tRr7ujp","level":1,"time":"2023-05-26T14:19:40+02:00","remoteAddr":"hidden.ip","user":"user","app":"no app in context","method":"GET","url":"/core/preview?fileId=3091531&x=250&y=250","message":"Deprecated event type for OCP\\IPreview:PreviewRequested: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36","version":"26.0.2.1","data":[]}
```

**Comment by artonge** [comment]
Can you double-check that the source files got correctly replaced?
Especially what's in `lib/E2EEnabledPathCache.php`?

**Comment by Dual-0** [comment]
/var/www/nextcloud/apps/end_to_end_encryption# cat lib/E2EEnabledPathCache.php
```
<?php

declare(strict_types=1);

/**
 * @copyright Copyright (c) 2022 Carl Schwan <carl@carlschwan.eu>
 *
 * @license GNU AGPL version 3 or any later version
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

namespace OCA\EndToEndEncryption;

use OCP\Files\Node;
use OCP\Files\Storage\IStorage;
use OCP\Files\IHomeStorage;
use OCP\Files\Cache\ICache;
use OCP\Cache\CappedMemoryCache;
use OCP\Files\NotFoundException;

class E2EEnabledPathCache {
        /**
         * @psalm-type EncryptedState=bool
         *
         * @psalm-type FileId=int
         */

        private CappedMemoryCache $perStorageEncryptedStateCache;

        public function __construct() {
                $this->perStorageEncryptedStateCache = new CappedMemoryCache();
        }

        /**
         * Checks if the path is an E2E folder or inside an E2E folder
         */
        public function isE2EEnabledPath(Node $node): bool {
                if ($node->isEncrypted()) {
                        return true;
                }
                $storage = $node->getStorage();
                $cache = $storage->getCache();
                return $this->getEncryptedStates($cache, $node, $storage);
        }

        /**
         * Get the encryption state for the path
         */
        protected function getEncryptedStates(ICache $cache, $node, IStorage $storage): bool {
                if (!$storage->instanceOfStorage(IHomeStorage::class)) {
                        return false;
                }

                $storageId = (string)$cache->getNumericStorageId();
                if (!isset($this->perStorageEncryptedStateCache[$storageId])) {
                        $this->perStorageEncryptedStateCache[$storageId] = [];
                }
                if (isset($this->perStorageEncryptedStateCache[$storageId][$node->getId()])) {
                        return $this->perStorageEncryptedStateCache[$storageId][$node->getId()];
                }

                if ($node->getPath() === '/') {
                        // root is never encrypted
                        $this->perStorageEncryptedStateCache[$storageId][$node->getId()] = false;
                        return false;
                }

                if ($node->isEncrypted()) {
                        // no need to go further down in the tree
                        $this->perStorageEncryptedStateCache[$storageId][$node->getId()] = true;
                        return true;
                }

                try {
                        $parentNode = $node->getParent();
                } catch (NotFoundException $e) {
                        $this->perStorageEncryptedStateCache[$storageId][$node->getId()] = false;
                        return false;
                }
                $encrypted = $this->getEncryptedStates($cache, $parentNode, $storage);
                $this->perStorageEncryptedStateCache[$storageId][$node->getId()] = $encrypted;
                return $encrypted;
        }
}
```

**Comment by Dual-0** [comment]
I will check this. Thx
